### ISSUE TITLE
FE/IN: Availability

### ISSUE THREAD

**Issue by rajivtitus** [hatchways/team-breadsticks#92]
- Create a FE for availability 
- Integrate this page with the profile on the BE

After signup, a user should be able to toggle themselves as a 'sitter' which would display the 'Availability' page where they input their price and availability for service

**Comment by iamalx** [comment]
hi @rajivtitus is the date range only for one time and they have to update it every week? Or do they only update once and that should apply for every week 
![image](https://user-images.githubusercontent.com/39109614/135766807-431f4d9a-a653-4d7a-a30a-e8ffd495af2c.png)

**Comment by ugur-akin** [comment]
I think it would be fine to go with what you think is better in terms of UX. If you're not sure, let us know and we can discuss it further 👍🏼

**Comment by rajivtitus** [comment]
Hi @iamalx! 

To keep things simple, it would be better to update it once and use the same availability for the following weeks (Sun - Sat each week)

**Comment by iamalx** [comment]
@ugur-akin OKAY, I already had the some logic for a defined week, but I will change it to update it once since it makes more sense
